### PR TITLE
[ fix ] Make early-terminating coverage check be more useful

### PR DESCRIPTION
**Pull request by buzden**
Export obviously forgotten to be exported function that turns on coverage check mode

### CODE REVIEW

**Comment by buzden** [comment]
I feel myself a bit instusive, but (as in some other your projects) I suggest myself to be added to the collaborators for this project in order to be able to merge such fixes without interrupting you

**Comment by buzden** [comment]
I've added another small fix around coverage checking to this PR in a separate commit, they are somewhat related

**Comment by buzden** [comment]
> while still preserving the old default

To be honest, all my experience with the Wilson bounds (mostly with checks of distribution of derived generators in DepTyCheck, but now also with generation data for testing the normalised compression distance) tells that they work nicely only after ~300 samples, not 100. So, maybe, it is good to set the default to be 300 instead of 100, as it is currently.

**Comment by stefan-hoeck** [comment]
Sorry for the late response. This looks very good to me. I'll merge it as it is and we can tune them default number of tests in another PR. For me, it would be fine to use a default of 300 or even 500.

**Pull request merged**
